config/routes.rb
Rails.application.routes.draw do
 devise_for :users
 root to: 'homes#top'
 get 'home/about' => 'homes#about'

 resources :bars, only: [:new, :create, :index, :show, :destroy, :edit, :update] do

  resource :favorites, only: [:create, :destroy]
  resources :comments, only: [:create, :destroy]
end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:index, :show, :edit, :update]

  resources :relationships, only: [:create, :destroy]
  get 'followings/:id' => 'relationships#followings', as: 'followings'
  get 'followers/:id' => 'relationships#followers', as: 'followers'

  # お問い合わせフォーム
  resources :contacts, only: [:new, :create]
  post 'contacts/confirm', to: 'contacts#confirm', as: 'confirm'
  post 'contacts/back', to: 'contacts#back', as: 'back'
  get 'done', to: 'contacts#done', as: 'done'

  get '/search', to: 'searchs#search'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bar.rb
class Bar < ApplicationRecord
  belongs_to :user
   # 画像アップ用のメソッド
  attachment :image

  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  validates :bar_name, presence: true, length: {maximum: 20}
  validates :caption, presence: true
  validates :image, presence: true
# 地図機能
  geocoded_by :address
  after_validation :geocode
# いいね機能
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
end

app/models/bar_image.rb
class BarImage < ApplicationRecord
 belongs_to :bar
 attachment :image
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :bar
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :bar
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :user
  belongs_to :follow, class_name: 'User'

  validates :user_id, presence: true
  validates :follow_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :bars, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  attachment :profile_image

  has_many :relationships
  has_many :followings, through: :relationships, source: :follow
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id'
  has_many :followers, through: :reverse_of_relationships, source: :user

  def follow(other_user)
    relationships.find_or_create_by(follow_id: other_user.id) unless self == other_user
  end

  def unfollow(other_user)
    relationship = relationships.find_by(follow_id: other_user.id)
    relationship.destroy if relationship
  end

  def following?(other_user)
    followings.include?(other_user)
  end
end

app/controllers/bars_controller.rb
class BarsController < ApplicationController
  def new
    @bar = Bar.new
  end

  def create
    @bar = Bar.new(bar_params)
    @bar.user_id = current_user.id
    if @bar.save
      redirect_to bars_path
    else
      render :new
    end
  end

  def index
    @bars = Bar.page(params[:page]).reverse_order
  end

  def show
    @bar = Bar.find(params[:id])
    @comment = Comment.new
  end

  def edit
    @bar = Bar.find(params[:id])
    redirect_to bars_path if current_user.id != @bar.user.id
    @user = current_user
  end

  def update
    @bar = Bar.find(params[:id])
    if @bar.update(bar_params)
      redirect_to bar_path(@bar.id), notice: 'You have updated Bar successfully.'
    else
      render 'edit'
    end
  end

  def destroy
    @bar = Bar.find(params[:id])
    @bar.destroy
    redirect_to bars_path
  end

  private

  def bar_params
    params.require(:bar).permit(:bar_name, :image, :caption, :address, )
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    bar = Bar.find(params[:bar_id])
    comment = current_user.comments.new(comment_params)
    comment.bar_id = bar.id
    comment.save
    redirect_to bar_path(bar)
  end

  def destroy
    Comment.find_by(id: params[:id]).destroy
    redirect_to bar_path(params[:bar_id])
  end

  private

  def comment_params
    params.require(:comment).permit(:comment)
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end

  # 確認画面
  def confirm
    @contact = Contact.new(contact_params)
    render :new if @contact.invalid?
  end

  def back
    @contact = Contact.new(contact_params)
    render :new
  end

  # 実際に送信
  def create
    @contact = Contact.new(contact_params)
    if @contact.save
      ContactMailer.send_mail(@contact).deliver_now
      redirect_to done_path
    else
      render :new
    end
  end

  # 送信完了画面
  def done
  end

  private

  def contact_params
    params.require(:contact)
          .permit(:email,
                  :name,
                  :phone_number,
                  :subject,
                  :message)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/searchs_controller.rb
class SearchsController < ApplicationController
  def search
    # viewのフォームタグ
    @model = params['model']
    @content = params['content']
    @method = params['method']
    @records = search_for(@model, @content, @method)
  end

  private

  def search_for(model, content, method)
    # ユーザー検索
    if model == 'user'
      if method == 'perfect'
        User.where(name: content)
      else
        User.where('name LIKE ?', '%' + content + '%')
      end
      # バー検索
    elsif model == 'bar'
      if method == 'perfect'
        Bar.where(bar_name: content)
      else
        Bar.where('bar_name LIKE ?', '%' + content + '%')
      end
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
    @book = Bar.new
    @user = current_user
  end

  def show
    @user = User.find(params[:id])
    @bars = @user.bars.page(params[:page]).reverse_order
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user.id), notice: 'You have updated User successfully.'
    else
      render 'edit'
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bars_helper.rb
module BarsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/searchs_helper.rb
module SearchsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/bars/_search.html.erb
<table class="table">
  <thead>
    <tr>
      <th scope="col"></th>
      <th scope="col">Bar Name</th>
      <th scope="col"></th>
      <th scope="col"></th>
    </tr>
  </thead>


    <tbody>
    <% bars.each do |bar| %>
      <tr>
        <td><%= attachment_image_tag bar, :image, :fill, 200, 200, format: 'jpeg', fallback: "no_image.jpg" %></td>
        <td><%= link_to bar.bar_name, bar_path(bar) %></td>
      </tr>
    <% end %>
    </tbody>
</table>

app/views/bars/edit.html.erb
<h1>Editing Bar</h1>

<%= form_with model:@bar,local:true do |f| %>
<div class="form-group">
  <%= f.label :bar_name %>
  <%= f.text_field :bar_name, class: 'form-control book_title' %>
</div>
<div class="form-group">
  <%= f.label :caption %>
  <%= f.text_area :caption, class: 'form-control book_body' %>
</div>
<div class="form-group">
  <%= f.submit class: 'btn btn-success' %>
</div>
<div>
<%= link_to 'Show', bar_path(@bar), class: "bark_#{@bar.id}" %> |
<%= link_to 'Back', bars_path, class: "back" %>
</div>
<% end %>

app/views/bars/index.html.erb
<div class="card-list-container py-5">
  <h1 class="text-center">Bar Lists</h1>
  <% @bars.each do |bar| %>
  <div class="card w-50 mx-auto mt-4 shadow-lg">
    <%= link_to bar_path(bar.id) do %>
      <%= attachment_image_tag bar, :image, class:"card-img-top"; %>
    <% end %>
    <div class="card-body">
      <div class="row">
        <div class="col-2">
          <%= attachment_image_tag bar.user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg", class:"mt-3 rounded-circle"; %>
        </div>
        <div class="col-10">
          <p class="card-title">
            <%= link_to(bar_path(bar.id), class:"text-dark") do %>
              <strong><i class="far fa-flag"></i><span> <%= bar.bar_name %></span></strong>
            <% end %>
          </p>
          <p class="card-text">説明：<%= bar.caption %></p>
          <span><i class="fas fa-user"></i> By <%= bar.user.name %> ｜ </span>
          <span><%= link_to "#{bar.comments.count} コメント", bar_path(bar.id), class:"text-dark" %> ｜ </span>
          <span id="favorite_buttons_<%= bar.id %>"><%= render "favorites/favorite", bar: bar %></span>
        </div>
      </div>
    </div>
  </div>
  <% end %>

<%= paginate @bars %>
</div>

app/views/bars/new.html.erb
<div class="container">
  <div class="row no-gutters">
    <div class="col-md-5 col-sm-10 mx-2 mx-sm-auto shadow-lg rounded px-0 my-5">
      <h5 class="text-dark bg-light p-4 mb-0">Bar Post</h5>
      <div class="form-body p-4">
        <% if @bar.errors.any? %>
          <%= @bar.errors.count %>件のエラーが発生しました
          <% @bar.errors.full_messages.each do |message| %>
            <%= message %>
          <% end %>
        <% end %>
        <!--複数画像追加-->
         <!--終わり-->
        <%= form_with model: @bar, local:true do |f| %>
          <%= f.attachment_field :image, class: "w-100" %>
          <div class="input-group mb-3 mt-4">
            <div class="input-group-prepend">
              <span class="input-group-text" aria-hidden="true"><i class="fas fa-building"></i></span>
            </div>
            <%= f.text_field :bar_name, class:"form-control", placeholder:"Bar Name" %>
          </div>
          <%= f.text_field :address, class:"form-control", placeholder:"Adress" %>
          <p></p>
          <%= f.text_area :caption, class:"form-control", rows:"3", placeholder:"説明" %>
          <hr>
          <%= f.submit '投稿', class:"btn btn-lg btn-block btn-secondary mt-4" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/bars/show.html.erb
<h1 class="text-center">Bar Detail</h1>
<div class='container'>
  <div class='row'>
    <div class='col-lg-5'>
    <div>
      <%= attachment_image_tag @bar, :image, :fill, 400, 400 %>
      <p>ショップ名：<%= @bar.bar_name %></p>
      <p>説明：<%= @bar.caption %></p>
      <p>ユーザーネーム：<%= @bar.user.name %></p>
      <p>投稿日時：<%= @bar.created_at.strftime('%Y/%m/%d') %></p>
      <% if @bar.user == current_user %>
        <%= link_to 'Edit', edit_bar_path(@bar) %>
        <%= link_to "Delete", bar_path(@bar), method: :delete, data: { confirm: "削除しますか？" } %>
      <% end %>
      <div id="favorite_buttons_<%= @bar.id %>">
        <%= render "favorites/favorite", bar: @bar %>
      </div>
    </div>
    <div>
      <p>コメント件数：<%= @bar.comments.count %></p>
      <% @bar.comments.each do |comment| %>
        <%= comment.user.name %>
        <%= comment.created_at.strftime('%Y/%m/%d') %><%= comment.comment %>
      <!--コメント者がログインユーザーなら削除可能-->
        <% if comment.user == current_user %>
          <div>
            <%= link_to "削除", bar_comment_path(comment.bar, comment), method: :delete %>
          </div>
        <% end %>
      <% end %>
    </div>
    <div>
      <%= form_with(model:[@bar, @comment], local: true) do |f| %>
        <%= f.text_area :comment, rows:'5',placeholder: "コメントをここに" %>
        <%= f.submit "送信する" %>
      <% end %>
    </div>
  </div>
  <div class='col-lg-7'>
    <div id="gmap"></div>
    <style>
      #gmap {
        height: 400px;
        width: 650px;
      }
    </style>
      <!--住所情報が無ければ下記scriptの実行をさせない。-->
    <% if @bar.latitude.present? && @bar.longitude.present? %>
      <script>
        let map

        function initMap(){
          geocoder = new google.maps.Geocoder()
          var test ={lat: <%= @bar.latitude %>, lng: <%= @bar.longitude %>};

          map = new google.maps.Map(document.getElementById('gmap'), {
            center: test,
            zoom: 15,
          });

          var contentString = '住所：<%= @bar.address %>';
          var infowindow = new google.maps.InfoWindow({
            content: contentString
          });

          marker = new google.maps.Marker({
            position:  test,
            map: map,
            title: contentString
          });
        }
      </script>
      <script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['API_KEY']%>&callback=initMap" async defer></script>
    <% end %>
  </div>
</div>

app/views/contacts/confirm.html.erb
<table>
  <tbody>
    <tr>
     <td class="text-center" style="width: 30%;">subject</td>
      <td><%= @contact.subject %></td>
     </tr>
    <tr>
     <td class="text-center" style="width: 30%;">Name</td>
      <td><%= @contact.name %></td>
     </tr>
      <td class="text-center" style="width: 30%;">Email</td>
      <td><%= @contact.email %></td>
     </tr>
     <tr>
      <td class="text-center">Messge</td>
      <td style="white-space: pre-wrap;"><%= @contact.message %></td>
    </tr>
  </tbody>
</table>

<%= form_for(@contact) do |f| %>
  <%= f.hidden_field :name %>
  <%= f.hidden_field :email %>
  <%= f.hidden_field :phone_number %>
  <%= f.hidden_field :subject %>
  <%= f.hidden_field :message %>
  <div><%= f.submit '　　送信　　' %></div>
<% end %>
<%= form_for @contact, url: back_path do |f| %>
  <%= f.hidden_field :name %>
  <%= f.hidden_field :email %>
  <%= f.hidden_field :phone_number %>
  <%= f.hidden_field :subject %>
  <%= f.hidden_field :message %>
  <div><%= f.submit '入力画面に戻る' %></div>
<% end %>

app/views/contacts/done.html.erb
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
</head>
 <body>
  <div class="container">
    　 <p class="text-center">お問い合わせが完了しました。</p>
    　  <p class="text-center">お問い合わせ内容につきましては、3日程度を目処に担当者よりご回答させていただきます。いましばらくお待ちくださいませ。</p>
    　  <p class="text-center"> 今後ともご愛顧賜りますようよろしくお願い申し上げます。</p>

  </div>
 </body>
</html>

app/views/contacts/new.html.erb
<h1>お問い合わせフォーム</h1>

<%= form_for(@contact, url: confirm_path) do |f| %>
  <div class="form-group">
    <%= f.label :subject, 'subject*' %>
    <%= f.text_field :subject, autofocus: true, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :name, 'name*' %>
    <%= f.text_field :name, autofocus: true, class: 'form-control' %>
  </div>
   <div class="form-group">
    <%= f.label :email, 'email*' %>
    <%= f.text_field :email, autofocus: true, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :message, 'message*' %>
    <%= f.text_area :message, size: '8x8', class: 'form-control' %>
  </div>

  <div>
    <%= f.submit '入力内容の確認' %>
  </div>
<% end %>

app/views/users/_index.html.erb
<table class='table'>
  <thead>
    <tr>
     <th class="image">image</th>
      <th class="name">name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
   <% @users.each do |user| %>
      <tr>
        <td><%= attachment_image_tag user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %></td>
        <td><%= user.name %></td>
        <td><%= user.introduction %></td>
          <!--フォロー機能追記-->
        <td>フォロー数：  <%= user.followings.count %></td>
        <td>フォロワー数： <%= user.followers.count %></td>
        <td><%= render 'relationships/follow_button', user: user %>　</td>

        <!--フォローボタン記載-->
        <td><%= link_to 'Show', user_path(user), class: "user_#{user.id}" %></td>
      </tr>
    <% end %>
  <tbody>
  </tbody>
</table>

app/views/users/_info.html.erb
<table class='table'>
  <tr><%= attachment_image_tag(user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg") %></tr>
  <tr>
	  <th>name</th>
	  <th><%= user.name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= user.introduction %></th>
   <tr>
    <th>fllows</th>
    <th><%= link_to user.followings.count, followings_path(user.id) %></th>
   </tr>
   <tr>
    <th>fllowers</th>
    <th><%= link_to user.followers.count, followers_path(user.id) %> </th>
   </tr>
  </tr>
 
</table>

<div class='row'>
  <% if user.id == current_user.id %>
  <%= link_to 'プロフィール編集',edit_user_path(user),class: "btn btn-outline-secondary btn-block fas fa-user-cog edit_user_#{user.id}" %>
  <% end %>
</div>

app/views/users/_search.html.erb
<table class="table">
  <thead>
    <tr>
      <th scope="col"></th>
      <th scope="col">Name</th>
      <th scope="col"></th>
      <th scope="col"></th>
    </tr>
    <% users.each do |user| %>
    <tr>
     <td><%= attachment_image_tag user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %></td>
     <td> <%= link_to user.name, user_path(user) %></td>
     <% end %>
  </thead>
</table>

app/views/users/edit.html.erb
 <div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>Profile editing</h2>
    <%= form_with model:@user, local:true do |f| %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control name" %>
      </div>
     <div class="form-group">
        <%= f.label :image %>
        <%= f.attachment_field :profile_image, class: "form-control-file user_image" %>
      </div>
      <div class="form-group">
        <%= f.label :introduction %>
        <%= f.text_area :introduction, class: "form-control introduction" %>
      </div>
      <div class="form-group">
        <%= f.submit class: 'btn btn-secondary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
        <%= render 'info', user: current_user %>
    </div>

      <div class='col-md-8 offset-md-1'>
      <h2>Users</h2>
      <%= render 'index',users: @users %>
  </div>
 </div>
</div>

app/views/users/show.html.erb
<div class='container px-5 px-sm-0'>
    <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
        <%= render 'users/info', user: @user %>
      <td><%= render 'relationships/follow_button', user: @user %>　</td>
    </div>
<div class='col-md-9'>
<div class="card-list-container py-1">
  <% @bars.each do |bar| %>
  <div class="card w-55 mx-auto mt-0 shadow-lg">
    <%= link_to bar_path(bar.id) do %>
      <%= attachment_image_tag bar, :image, class:"card-img-top"; %>
    <% end %>
    <div class="card-body">
      <div class="row">
        <div class="col-2">
          <%= attachment_image_tag bar.user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg", class:"mt-3 rounded-circle"; %>
        </div>
        <div class="col-10">
          <p class="card-title">
            <%= link_to(bar_path(bar.id), class:"text-dark") do %>
              <strong><i class="far fa-flag"></i><span> <%= bar.bar_name %></span></strong>
            <% end %>
          </p>
          <p class="card-text">説明：<%= bar.caption %></p>
          <span><i class="fas fa-user"></i> By <%= bar.user.name %> ｜ </span>
          <span><%= link_to "#{bar.comments.count} コメント", bar_path(bar.id), class:"text-dark" %> ｜ </span>
        </div>
      </div>
    </div>
  </div>
  <% end %>
 <%= paginate @bars %>
 </div>
 </div>
 </div>
</div>