config/routes.rb
Rails.application.routes.draw do
 devise_for :users
 root to: 'homes#top'
 get 'home/about' => 'homes#about'

 resources :bars, only: [:new, :create, :index, :show, :destroy, :edit, :update] do

  resource :favorites, only: [:create, :destroy]
  resources :comments, only: [:create, :destroy]
end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:index, :show, :edit, :update]

  resources :relationships, only: [:create, :destroy]
  get 'followings/:id' => 'relationships#followings', as: 'followings'
  get 'followers/:id' => 'relationships#followers', as: 'followers'

  # お問い合わせフォーム
  resources :contacts, only: [:new, :create]
  post 'contacts/confirm', to: 'contacts#confirm', as: 'confirm'
  post 'contacts/back', to: 'contacts#back', as: 'back'
  get 'done', to: 'contacts#done', as: 'done'

  get '/search', to: 'searchs#search'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bar.rb
class Bar < ApplicationRecord
  belongs_to :user
   # 画像アップ用のメソッド
  attachment :image

  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  validates :bar_name, presence: true, length: {maximum: 20}
  validates :caption, presence: true
  validates :image, presence: true
# 地図機能
  geocoded_by :address
  after_validation :geocode
# いいね機能
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
end

app/models/bar_image.rb
class BarImage < ApplicationRecord
 belongs_to :bar
 attachment :image
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :bar
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :bar
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :user
  belongs_to :follow, class_name: 'User'

  validates :user_id, presence: true
  validates :follow_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :bars, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  attachment :profile_image

  has_many :relationships
  has_many :followings, through: :relationships, source: :follow
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id'
  has_many :followers, through: :reverse_of_relationships, source: :user

  def follow(other_user)
    relationships.find_or_create_by(follow_id: other_user.id) unless self == other_user
  end

  def unfollow(other_user)
    relationship = relationships.find_by(follow_id: other_user.id)
    relationship.destroy if relationship
  end

  def following?(other_user)
    followings.include?(other_user)
  end
end

app/controllers/bars_controller.rb
class BarsController < ApplicationController
  def new
    @bar = Bar.new
  end

  def create
    @bar = Bar.new(bar_params)
    @bar.user_id = current_user.id
    if @bar.save
      redirect_to bars_path
    else
      render :new
    end
  end

  def index
    @bars = Bar.page(params[:page]).reverse_order
  end

  def show
    @bar = Bar.find(params[:id])
    @comment = Comment.new
  end

  def edit
    @bar = Bar.find(params[:id])
    redirect_to bars_path if current_user.id != @bar.user.id
    @user = current_user
  end

  def update
    @bar = Bar.find(params[:id])
    if @bar.update(bar_params)
      redirect_to bar_path(@bar.id), notice: 'You have updated Bar successfully.'
    else
      render 'edit'
    end
  end

  def destroy
    @bar = Bar.find(params[:id])
    @bar.destroy
    redirect_to bars_path
  end

  private

  def bar_params
    params.require(:bar).permit(:bar_name, :image, :caption, :address, )
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    bar = Bar.find(params[:bar_id])
    comment = current_user.comments.new(comment_params)
    comment.bar_id = bar.id
    comment.save
    redirect_to bar_path(bar)
  end

  def destroy
    Comment.find_by(id: params[:id]).destroy
    redirect_to bar_path(params[:bar_id])
  end

  private

  def comment_params
    params.require(:comment).permit(:comment)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/searchs_controller.rb
class SearchsController < ApplicationController
  def search
    # viewのフォームタグ
    @model = params['model']
    @content = params['content']
    @method = params['method']
    @records = search_for(@model, @content, @method)
  end

  private

  def search_for(model, content, method)
    # ユーザー検索
    if model == 'user'
      if method == 'perfect'
        User.where(name: content)
      else
        User.where('name LIKE ?', '%' + content + '%')
      end
      # バー検索
    elsif model == 'bar'
      if method == 'perfect'
        Bar.where(bar_name: content)
      else
        Bar.where('bar_name LIKE ?', '%' + content + '%')
      end
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
    @book = Bar.new
    @user = current_user
  end

  def show
    @user = User.find(params[:id])
    @bars = @user.bars.page(params[:page]).reverse_order
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user.id), notice: 'You have updated User successfully.'
    else
      render 'edit'
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bars_helper.rb
module BarsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/searchs_helper.rb
module SearchsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/homes/about.html.erb
<main>
 <div class='container'>
  <div class='row'>
    <h1 class="px-3 mx-auto">Welcome to <i class="fas fa-glass-martini-alt"></i></i><strong>Bar Hopper</strong>!</h1>
  </div>
  <p></p>
  <h3 class="text-center">Bar Hopperでは<i class="fas fa-cocktail"></i>をこよなく愛する人の為のサイトです。</h3>
  <p></p>
  <h3 class="text-center">皆様でオススメのBarを紹介共有しちゃいましょう！！</h3>
  <p></p>
  <div class="row">
   <i class="fas fa-mail-bulk"></i>
   <%= link_to 'お問い合わせ', new_contact_path, class: 'nav-link text-dark' %>
  </div>
 </div>
</main>

app/views/homes/top.html.erb
<div class="container">
  <div class="row">
    <div class='mx-auto col-11 col-sm-10 col-lg-8 col-xl-6'>
      <h1 class="px-3 mx-auto">Welcome to <i class="fas fa-glass-martini-alt"></i></i><strong>Bar Hopper</strong>!</h1>
      <p class="text-center">Bar Hopperにログインを行い</p>
      <p class="text-center">店舗の共有と新しい店舗の出会いを行いましょう！！</p>
      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
          <%= link_to 'Log in',user_session_path, class: "btn btn-info btn-sm btn-block mb-3 sign_in" %>
        </div>
        <div class="row">
          <%= link_to 'Sign Up',new_user_registration_path, class: "btn btn-success btn-sm btn-block sign_up" %>
          <!--<div>Logo made by <a href="https://www.designevo.com/" title="Free Online Logo Maker">DesignEvo free logo creator</a></div>-->
      </div>
    </div>
  </div>
</div>

app/views/searchs/_form.html.erb
<% if user_signed_in? %>
    <%= form_tag(search_path, method: :get) do %>
      <%= text_field_tag 'content' %>
      <%= select_tag 'model', options_for_select({ "User" => "user", "Bar" => "bar" }) %>
      <%= select_tag 'method', options_for_select({ "完全一致" => "perfect", "部分一致" => "partial" }) %>
      <%= submit_tag '検索' %>
    <% end %>
<% end %>

app/views/searchs/search.html.erb
<% if @model == 'user' %>
  <h3>【Usersモデルの検索結果】検索ワード：<%= @content %></h3>
  <%= render 'users/search', users: @records %>
<% else @model == 'bars' %>
  <h3>【Barsモデルの検索結果】検索ワード：<%= @content %></h3>
    <%= render 'bars/search', bars: @records %>
<% end %>