config/routes.rb
Rails.application.routes.draw do
 devise_for :users
 root to: 'homes#top'
 get 'home/about' => 'homes#about'

 resources :bars, only: [:new, :create, :index, :show, :destroy, :edit, :update] do

  resource :favorites, only: [:create, :destroy]
  resources :comments, only: [:create, :destroy]
end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:index, :show, :edit, :update]

  resources :relationships, only: [:create, :destroy]
  get 'followings/:id' => 'relationships#followings', as: 'followings'
  get 'followers/:id' => 'relationships#followers', as: 'followers'

  # お問い合わせフォーム
  resources :contacts, only: [:new, :create]
  post 'contacts/confirm', to: 'contacts#confirm', as: 'confirm'
  post 'contacts/back', to: 'contacts#back', as: 'back'
  get 'done', to: 'contacts#done', as: 'done'

  get '/search', to: 'searchs#search'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bar.rb
class Bar < ApplicationRecord
  belongs_to :user
   # 画像アップ用のメソッド
  attachment :image

  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  validates :bar_name, presence: true, length: {maximum: 20}
  validates :caption, presence: true
  validates :image, presence: true
# 地図機能
  geocoded_by :address
  after_validation :geocode
# いいね機能
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
end

app/models/bar_image.rb
class BarImage < ApplicationRecord
 belongs_to :bar
 attachment :image
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :bar
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :bar
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :user
  belongs_to :follow, class_name: 'User'

  validates :user_id, presence: true
  validates :follow_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :bars, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  attachment :profile_image

  has_many :relationships
  has_many :followings, through: :relationships, source: :follow
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id'
  has_many :followers, through: :reverse_of_relationships, source: :user

  def follow(other_user)
    relationships.find_or_create_by(follow_id: other_user.id) unless self == other_user
  end

  def unfollow(other_user)
    relationship = relationships.find_by(follow_id: other_user.id)
    relationship.destroy if relationship
  end

  def following?(other_user)
    followings.include?(other_user)
  end
end

app/controllers/bars_controller.rb
class BarsController < ApplicationController
  def new
    @bar = Bar.new
  end

  def create
    @bar = Bar.new(bar_params)
    @bar.user_id = current_user.id
    if @bar.save
      redirect_to bars_path
    else
      render :new
    end
  end

  def index
    @bars = Bar.page(params[:page]).reverse_order
  end

  def show
    @bar = Bar.find(params[:id])
    @comment = Comment.new
  end

  def edit
    @bar = Bar.find(params[:id])
    redirect_to bars_path if current_user.id != @bar.user.id
    @user = current_user
  end

  def update
    @bar = Bar.find(params[:id])
    if @bar.update(bar_params)
      redirect_to bar_path(@bar.id), notice: 'You have updated Bar successfully.'
    else
      render 'edit'
    end
  end

  def destroy
    @bar = Bar.find(params[:id])
    @bar.destroy
    redirect_to bars_path
  end

  private

  def bar_params
    params.require(:bar).permit(:bar_name, :image, :caption, :address, )
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
    @book = Bar.new
    @user = current_user
  end

  def show
    @user = User.find(params[:id])
    @bars = @user.bars.page(params[:page]).reverse_order
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user.id), notice: 'You have updated User successfully.'
    else
      render 'edit'
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bars_helper.rb
module BarsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/searchs_helper.rb
module SearchsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
 <footer class="fixed-bottom bg-dark text-white pt-5 pb-4">
    <div class='row'>
      <div class='mx-auto'>
        <p>Bar紹介SNS Bar Hopper</p>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      <a class="navbar-brand" href="/"><span>BarHoppe<i class="fas fa-glass-martini"></i></span></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
        <% if user_signed_in? %>
          <li><%= link_to 'Home', user_path(current_user), class: 'nav-link text-light' %></li>
          <li><%= link_to 'About', home_about_path, class: 'nav-link text-light' %></li>
          <li><%= link_to 'POST', new_bar_path, class: 'nav-link text-light' %></li>
          <li><%= link_to 'Bars', bars_path, class: 'nav-link text-light' %></li>
          <li><%= link_to 'Users', users_path, class: 'nav-link text-light' %></li>
          <li><%= link_to "Log Out", destroy_user_session_path, method: :delete, class: 'nav-link text-light' %></li>
          <li><%= render 'searchs/form' %></li>
        <% else %>
          <li><%= link_to 'Home', root_path, class: 'nav-link text-light' %></li>
          <li><%= link_to 'About', home_about_path, class: 'nav-link text-light' %></li>
          <li><%= link_to "Sign up", new_user_registration_path, class: 'nav-link text-light' %></li>
          <li><%= link_to "Log in", new_user_session_path, class: 'nav-link text-light' %></li>
        <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bar Hopper</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
   <%= render 'layouts/header' %>
  <body>
      <main>
        <p id="notice"><%= notice %></p>
         <%= yield %>
      </main>
   <%= render 'layouts/footer' %>
  </body>
</html>